import { ProductsSimpleNew } from '../../module/useProductSearch';

export const mockProducts: ProductsSimpleNew[] = [
  {
    id: '1',
    name: 'Toyota Corolla',
    slug: 'toyota-corolla',
    description: 'Reliable and efficient car',
    brand: 'Toyota',
    year: 2018,
    price: 15000,
    originalPrice: 17000,
    discount: 2000,
    images: ['image1.jpg', 'image2.jpg'],
    bodyColor: 'White',
    mileage: 50000,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    location: 'Berlin',
    horsepower: 132,
    condition: 'Used',
    categories: ['Sedan', 'Compact'],
  },
  {
    id: '2',
    name: 'Ford Mustang',
    slug: 'ford-mustang',
    description: 'Sporty muscle car',
    brand: 'Ford',
    year: 2020,
    price: 35000,
    originalPrice: 38000,
    discount: 3000,
    images: ['mustang1.jpg'],
    bodyColor: 'Red',
    mileage: 20000,
    transmission: 'Manual',
    fuelType: 'Gasoline',
    location: 'Munich',
    horsepower: 450,
    condition: 'Used',
    categories: ['Coupe', 'Sports'],
  },
];
